apiVersion: v1
data:
  SECRET: d2VuaW9lcnZpb3B3ZXJpcGdqYXdlcm9wZ2ppb3B3Z2ppb3dlcnAK
kind: Secret
metadata:
  annotations:
    # resource-replicator/replicate-to: "my-namespace"
    resource-replicator/all-namespaces: "true"
  name: test-secret
