apiVersion: v1
data:
  SECRET: d2VuaW9lcnZpb3B3ZXJpcGdqYXdlcm9wZ2ppb3B3Z2ppb3dlcnAK
kind: Secret
metadata:
  annotations:
    # resource-replicator/replicate-to: "my-namespace"
    resource-replicator/all-namespaces: "true"
  name: test-secret
---
apiVersion: v1
data:
  SECRET-REGEX: YjViMDRhM2E2NGMxZTA5YTdlYTcwODliNDM4M2Q3YzdlODg2MmI3ZDUxOTJhMTY0OGMzNmMzODUy
kind: Secret
metadata:
  annotations:
    resource-replicator/replicate-to: "my-namespace[0-9],kube.*"
  name: regex-secret
