apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  annotations:
    resource-replicator/all-namespaces: "true"
  name: test-cm
---
apiVersion: v1
data:
  key2: value2
kind: ConfigMap
metadata:
  annotations:
    resource-replicator/replicate-to: "my-namespace[0-9]"
  name: regex-cm
